name: Build Task

on:
  workflow_call:
    secrets:
      token:
        required: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: yarn install & build
        run: |
          yarn install
          yarn build

