name: Deploy task

on:
  push:
    branches:
      - main

jobs:
  test:
    uses: talo242/github-actions-app/.github/workflows/test.yml@main
    secrets:
      token: {{ secrets.GITHUB_TOKEN }}

  build:
    uses: talo242/github-actions-app/.github/workflows/build.yml@main
    secrets:
      token: {{ secrets.GITHUB_TOKEN }}