name: Deploy task

on:
  push:
    branches:
      - main

jobs:
  test:
    uses: talo242/github-actions-app/.github/workflows/test.yml@main
  build:
    uses: talo242/github-actions-app/.github/workflows/build.yml@main