name: Deploy task

on:
  push:
    branches:
      - main

jobs:
  test:
    uses: talo242/github-actions-app/.github/actions/test.yml@main
  build:
    uses: talo242/github-actions-app/.github/actions/build.yml@main