name: Pull Request task

on:
  pull_request:
    branches:
      - main

jobs:
  lint:
    uses: talo242/github-actions-test/.github/workflows/test.yml@main

  test:
    uses: talo242/github-actions-test/.github/workflows/test.yml@main

  update_release_notes:
    uses: talo242/github-actions-test/.github/workflows/release-drafter.yml@main
