name: Pull Request task

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    uses: talo242/github-actions-app/.github/workflows/test.yml@main

  update-release-notes:
    uses: talo242/github-actions-app/.github/workflows/release-drafter.yml@main